Completed week 2 assessment
learn-academy-2023-alpha/week-2-assessment-iraholmes pull request #1
Opened 2023-02-28 03:13 UTC by iraholmes

# Submitting Week 2 Assessment

### ✅ Completed Files

Select the following as confirmation that the files in this repository are complete.

- [✅  ] Coding Challenges
- [ ✅ ] Coding Concepts
- [✅  ] Interview Questions

### 📝 Feedback

If you would like specific feedback on a particular problem please leave details here:
I would like to get more information about what I was missing on the final jest question, I felt that I got so close then got lost. 
Also on the last question in the coding concepts section. Thank you

2023-03-01 02:38 UTC, Genemichael25 requested changes
Ira, I am requesting changes for the following reasons: code challenges #2 test/code needs to be refactored for the question, #3 not sufficient pseudocode. Coding concept #1 needs verification and explanation. Please let us know if you don't understand a question, or need clarification on the feedback I have left throughout.

2023-03-01 02:38 UTC, Genemichael25 commented on code-challenges.test.js
> +}
Great job on this function! You don't need to check if the number % 3 === 0 twice, I would get rid of the else if and return on line 55-56. Other than that, looks good!

2023-03-01 02:38 UTC, Genemichael25 commented on code-challenges.test.js
> +
The intent with this challenge is to capitalize the first letter of the strings in an array. What do you mean by connect allCaps variable to both arrays?

2023-03-01 02:38 UTC, Genemichael25 commented on code-challenges.test.js
> +// Test Suites: 1 passed, 1 total
Do we need randomNouns in our function?

2023-03-01 02:38 UTC, Genemichael25 commented on code-challenges.test.js
> +//
This pseudocode isn't enough to start visualizing how we can create the code for this problem.

2023-03-01 02:38 UTC, Genemichael25 commented on coding-concepts.js
>  // b) Verify and explain:
Missing verification and explanation.

2023-03-01 02:38 UTC, Genemichael25 commented on coding-concepts.js
> +// b) Verify and explain:[ 8, 10, 12, 14, 16 ] An array of all numbers multiplied by 2, because the .map() method ran each array number through the * 2 action and returned them.
Exactly, great job explaining this one!

2023-03-01 02:38 UTC, Genemichael25 commented on coding-concepts.js
> +// b) Verify and explain: JavaScript, the entire first word in the string was returned. The string at the 0 index was returned.
Why was just JavaScript returned?

2023-03-01 02:38 UTC, Genemichael25 commented on interview-questions.md
> +Researched answer: Iteration is the protocol that runs the code to the next operator to return a value or true / false response.
Iteration is performing something on each element in a collection. For example, with .map we can multiply the values in an array by a number. Going into each element is the iteration.

2023-03-03 22:01 UTC, elysemontano approved these changes
Thank you for making the changes Ira!  Keep working on setting up the test so that it is invoking the function with any arguments and comparing against a set expected output.  Also make sure to keep working on breaking down the problems into small pieces in your pseudocode. This will really help bring the logic together.  Please make sure to reach out if you need extra help.  We have some really great mentors that we can set you up with to give you some extra assistance.

2023-03-03 22:01 UTC, elysemontano commented on code-challenges.test.js
> +      expect(capNoun(randomNouns1[0])).toString("Streetlamp", "Potato", "Teeth", "Conclusions", "Nephew")
Keep in mind your test should not have any logic.  We want the test to simply invoke the function with any relevant arguments and check that the outcome equals an expected output.

2023-03-03 22:02 UTC, merged